//! `gen types` (spec 19): reflect the live schema through `catalog()` and emit a
//! single TypeScript file for the `@twilldb/bun` client — a row interface per
//! table, the engine's storage classes mapped to TS, `vector(N)` → `number[]`,
//! and a nullable column widened with `| null`. The app imports the file so
//! `db.query<Row>()` calls stay statically typed against the real schema.

use engine::{CatalogTable, ColumnType};

/// Generate the TypeScript source for every reflected table.
pub fn generate(tables: &[CatalogTable]) -> String {
    let mut out = String::from(
        "// Generated by `twilldb gen types` — do not edit by hand.\n\
         // Re-run after a schema change to keep these types in sync.\n\n",
    );
    if tables.is_empty() {
        out.push_str("// (no tables in the schema)\n");
        return out;
    }
    for t in tables {
        out.push_str(&format!("export interface {} {{\n", pascal_case(&t.name)));
        for c in &t.columns {
            let mut ts = ts_type(c.ty);
            if !c.not_null {
                ts.push_str(" | null");
            }
            out.push_str(&format!("  {}: {};\n", prop_name(&c.name), ts));
        }
        out.push_str("}\n\n");
    }
    out
}

/// Map an engine storage class to its TypeScript representation in the Bun client
/// (INTEGER/REAL → number, TEXT → string, BLOB → Uint8Array, vector → number[]).
fn ts_type(ty: ColumnType) -> String {
    match ty {
        ColumnType::Integer | ColumnType::Real => "number".to_string(),
        ColumnType::Text => "string".to_string(),
        ColumnType::Blob => "Uint8Array".to_string(),
        ColumnType::Vector(_) => "number[]".to_string(),
    }
}

/// A TypeScript property name: a valid bare identifier is emitted as-is, anything
/// else is quoted so the interface stays valid.
fn prop_name(name: &str) -> String {
    let valid = !name.is_empty()
        && name
            .chars()
            .next()
            .map(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
            .unwrap_or(false)
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if valid {
        name.to_string()
    } else {
        format!("\"{}\"", name.replace('"', "\\\""))
    }
}

/// PascalCase a table name for the interface name (`blog_posts` → `BlogPosts`).
/// A name with no usable leading letter is prefixed with `T` so it stays a valid
/// TS identifier.
fn pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if upper_next {
                out.push(c.to_ascii_uppercase());
            } else {
                out.push(c);
            }
            upper_next = false;
        } else {
            upper_next = true;
        }
    }
    if out.is_empty() || out.chars().next().unwrap().is_ascii_digit() {
        format!("T{out}")
    } else {
        out
    }
}
